### ISSUE TITLE
Synology/docker compatibility

### ISSUE THREAD

**Issue by Mewgood** [theodorosploumis/faaast#2]
Would this be too complicated to implement?

**Comment by theodorosploumis** [comment]
Can you please explain in details what do you mean by "compatibility"? This tool is already using Docker to make the builds.

Also, what is "Synology"?

**Comment by Mewgood** [comment]
Synology is a nas solution that makes it relatively easy to selfhost docker images. I gave it a shot to see if I could make this image work on it, but couldn't connect to it via the browser.

**Comment by Mewgood** [comment]
Synology is a nas solution that makes it relatively easy to selfhost docker images. I gave it a shot to see if I could make this image work on it, but couldn't connect to it via the browser.

By "compatibility", I just meant if you could make a branch that would work on Synology out of the box.

**Comment by theodorosploumis** [comment]
@Mewgood Link?

**Comment by Mewgood** [comment]
https://www.wundertech.net/how-to-use-docker-on-a-synology-nas/#how-to-dc

Here's an article on how to setup docker on a Synology nas and access the webservice on the local network :)

**Comment by theodorosploumis** [comment]
The docker image does not expose any port. In order to install the whole system (web UI that works with the docker image) see https://github.com/theodorosploumis/faaast/blob/master/scripts/server-install.sh.
